/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-09-11 03:24:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.vo.BoardVO;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	BoardVO bv = (BoardVO)request.getAttribute("bv"); 
	
// 	String board_content = "";
// 	if(bv.getBoard_content() != null){
// 		board_content = bv.getBoard_content().replaceAll(System.lineSeparator(), "<br>");
// 	}


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"update.do\" method=\"get\">\r\n");
      out.write("\t  <input type=\"hidden\" name=\"board_no\" value=\"");
      out.print( bv.getBoard_no() );
      out.write("\" >\r\n");
      out.write("\t\t<table board=\"1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>글 번호:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bv.getBoard_no());
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>제목:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bv.getBoard_title());
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>내용:</td>\r\n");
      out.write("\t\t\t<td><textarea>");
      out.print(bv.getBoard_content());
      out.write("</textarea></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>작성자:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(bv.getBoard_writer());
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t  \t<td colspan=\"2\">\r\n");
      out.write("\t\t  \t\t<a href=\"list.do\">[목록으로]</a>\r\n");
      out.write("\t\t  \t\t<a href=\"update.do?board_no=");
      out.print(bv.getBoard_no());
      out.write("\">[회원정보 수정]</a>\r\n");
      out.write("\t\t  \t\t<a href=\"delete.do?board_no=");
      out.print(bv.getBoard_no());
      out.write("\">[회원정보 삭제]</a>\r\n");
      out.write("\t\t  \t</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"회원수정\">\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
