/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-09-10 09:31:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.cmm.vo.FileVO;
import kr.or.ddit.member.vo.MemberVO;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO memVO = (MemberVO) request.getAttribute("memVO");
	// LineSeparator를 이용하여 <br>태그로 변경함. 
	String memAddr = "";
	
	FileVO fileVO = (FileVO) request.getAttribute("fileVO");
	
	if( memVO.getMem_addr() != null){
		memAddr = memVO.getMem_addr().replaceAll(System.lineSeparator(), "<br>");
	}



      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>신규회원 등록</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/updateMember\" method=\"get\">\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>I D:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(memVO.getMem_id());
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>이름:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(memVO.getMem_name());
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>전화번호:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(memVO.getMem_tel());
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>주소:</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(memAddr);
      out.write("</textarea></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>첨부파일:</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("  \t\t\t\t");
 if(fileVO != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a  href = \"");
      out.print(request.getContextPath());
      out.write("/filedownload.do?fileId=");
      out.print(fileVO.getAtchFileId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(fileVO.getOrignlFileNm() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t  \t<td colspan=\"2\">\r\n");
      out.write("\t\t  \t\t<a href=\"list.do\">[목록으로]</a>\r\n");
      out.write("\t\t  \t\t<a href=\"updateMember?memId=");
      out.print(memVO.getMem_id());
      out.write("\">[회원정보 수정]</a>\r\n");
      out.write("\t\t  \t\t<a href=\"delete.do?memId=");
      out.print(memVO.getMem_id());
      out.write("\">[회원정보 삭제]</a>\r\n");
      out.write("\t\t  \t</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"회원수정\">\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
